# To change this template, choose Tools | Templates
# and open the template in the editor.

#Client messages
CMSG_IDENTIFY = 0
CMSG_BLOCKCHANGE = 5
CMSG_POSITIONUPDATE = 8
CMSG_MESSAGE = 13
#End!
#Server Messages
SMSG_INITIAL = 0
SMSG_KEEPALIVE = 1
SMSG_PRECHUNK = 2
SMSG_CHUNK = 3
SMSG_LEVELSIZE = 4
SMSG_BLOCKCHANGE = 5
SMSG_BLOCKSET = 6
SMSG_SPAWNPOINT = 7
SMSG_PLAYERPOS = 8
SMSG_PLAYERDIR = 11
SMSG_PLAYERLEAVE = 12
SMSG_MESSAGE = 13
SMSG_ERROR = 14

#Sizes of CMSG packets.
PacketSizes = {
    CMSG_IDENTIFY: 130,
    CMSG_BLOCKCHANGE: 8,
    CMSG_POSITIONUPDATE: 9,
    CMSG_MESSAGE: 65
}
